---
title: 我的软件库
author: Dinghao Miao
date: '2020-07-12'
slug: 我的软件库
categories: []
tags:
  - 善用佳软
---
# Windows 自用软件库
1. 由 Geek Uninstaller 1.4.7 于 2020年7月12日 16:35:16 生成
2. 由https://tableconvert.com/ 进行Markdown转换

| 类别      | 程序名称                                              | 大小       | 安装时间               |
|---------|---------------------------------------------------|----------|--------------------|
| Excel插件 | 方方格子 版本 3\.6\.8\.0                                | 143 MB   | 14\.04\.2020 00:00 |
| Latex插件 | WordTeX                                           |          | 12\.07\.2020 16:19 |
| PPT插件   | iSlide Tools                                      | 307 MB   | 10\.07\.2020 10:14 |
| PPT插件   | think\-cell                                       | 156 MB   | 30\.06\.2020 22:28 |
| SNS     | 微信                                                | 119 MB   | 06\.07\.2020 11:28 |
| 办公软件    | Microsoft Office Professional Plus 2019 \- zh\-cn | 2\.72 GB | 18\.06\.2020 01:29 |
| 办公软件    | Microsoft Visio 专业版 2019 \- zh\-cn                | 3\.19 GB | 17\.12\.2019 16:41 |
| 办公软件    | XMind ZEN 10\.0\.0                                | 612 MB   | 15\.12\.2019 16:28 |
| 办公软件    | 蓝湖 Axure 1\.7\.0                                  | 148 MB   | 08\.11\.2019 19:28 |
| 办公软件    | Axure RP 9                                        | 458 MB   | 08\.10\.2019 14:47 |
| 办公软件    | Adobe XD                                          | 405 MB   | 08\.07\.2020 12:53 |
| 办公软件    | Adobe Photoshop Express                           | 45\.2 MB | 30\.06\.2020 18:29 |
| 编程工具    | Fork \- a fast and friendly git client            | 357 MB   | 05\.06\.2020 09:32 |
| 编程工具    | RStudio                                           | 718 MB   | 21\.10\.2019 20:37 |
| 编程工具    | Git version 2\.23\.0\.windows\.1                  | 640 MB   | 24\.09\.2019 00:00 |
| 编辑器     | Microsoft Visual Studio Code Insiders \(User\)    | 257 MB   | 12\.07\.2020 16:34 |
| 翻译      | 1Checker \- Outlook Plugin                        |          | 12\.07\.2020 16:24 |
| 翻译      | 1Checker 2\.1\.7\.0                               | 33\.4 MB | 12\.07\.2020 16:23 |
| 翻译      | 1Checker \- Word Plugin                           | 147 MB   | 08\.07\.2020 12:44 |
| 护眼工具    | f\.lux                                            |          | 17\.05\.2020 13:30 |
| 记账工具    | GnuCash 3\.8                                      | 588 MB   | 01\.02\.2020 00:00 |
| 浏览器     | Microsoft Edge                                    | 588 MB   | 09\.07\.2020 06:16 |
| 企业办公    | 企业微信                                              | 639 MB   | 07\.07\.2020 08:07 |
| 企业办公    | 云视讯                                               | 189 MB   | 03\.07\.2020 14:23 |
| 企业办公    | Zoom                                              | 103 MB   | 02\.07\.2020 17:21 |
| 企业办公    | 钉钉                                                | 406 MB   | 24\.06\.2020 09:12 |
| 企业办公    | 腾讯会议                                              | 172 MB   | 13\.06\.2020 12:59 |
| 去广告     | 阿呆喵广告拦截                                           | 13\.6 MB | 02\.08\.2019 12:58 |
| 上网工具    | Clash for Windows 0\.10\.4                        | 280 MB   | 30\.06\.2020 18:55 |
| 视频播放器   | ZY Player 1\.0\.23                                | 166 MB   | 24\.06\.2020 09:14 |
| 视频播放器   | PotPlayer                                         | 81\.6 MB | 26\.04\.2020 22:28 |
| 数据分析    | R for Windows 3\.6\.1                             | 195 MB   | 02\.08\.2019 00:00 |
| 网盘      | MEGAsync                                          | 73\.6 MB | 09\.07\.2020 00:46 |
| 网盘      | Dropbox                                           | 310 MB   | 07\.07\.2020 15:47 |
| 网盘      | Microsoft OneDrive                                | 133 MB   | 28\.06\.2020 18:41 |
| 文件管理    | calibre                                           | 299 MB   | 23\.06\.2020 11:57 |
| 文件检索    | Everything 1\.4\.1\.935 \(x86\)                   | 12\.7 MB | 02\.08\.2019 12:57 |
| 文件同步    | HandShaker                                        | 103 MB   | 25\.09\.2019 11:30 |
| 文件转换    | Pandoc 2\.10                                      | 349 MB   | 09\.07\.2020 14:36 |
| 下载工具    | Motrix 1\.5\.15                                   | 165 MB   | 13\.06\.2020 12:23 |
| 项目管理    | Microsoft Project 专业版 2019 \- zh\-cn              | 9\.17 GB | 18\.06\.2020 01:29 |
| 效率工具    | 腾讯桌面整理                                            | 53\.0 MB | 14\.05\.2020 20:18 |
| 效率工具    | TeraCopy version 3\.26                            | 14\.5 MB | 15\.08\.2019 00:00 |
| 效率工具    | Snipaste                                          | 42\.5 MB | 08\.07\.2020 17:41 |
| 效率工具    | Microsoft To Do                                   | 61\.4 MB | 07\.07\.2020 08:22 |
| 效率工具    | Sticky Notes                                      | 43\.1 MB | 11\.06\.2020 13:13 |
| 效率工具    | OneNote for Windows 10                            | 1\.46 GB | 29\.05\.2020 15:27 |
| 压缩工具    | 7\-Zip 19\.00 \(x64\)                             | 3\.68 MB | 26\.05\.2020 14:29 |
| 音乐软件    | 网易云音乐                                             | 87\.7 MB | 01\.07\.2020 12:19 |
| 音乐软件    | AIMP                                              | 47\.7 MB | 21\.10\.2019 00:00 |
| 语言软件    | 每日英语听力                                            | 347 MB   | 02\.06\.2020 14:29 |
| 语言软件    | 欧路词典                                              | 154 MB   | 01\.04\.2020 11:20 |
| 语言软件    | Anki                                              | 321 MB   | 12\.02\.2020 05:33 |
| 远程工具    | TeamViewer                                        | 97\.9 MB | 09\.07\.2020 10:22 |
| 阅读器     | NeatReader 5\.0\.4                                | 198 MB   | 05\.07\.2020 11:31 |
| 阅读器     | Adobe Acrobat DC                                  | 1\.76 GB | 02\.09\.2019 00:00 |
